name: Main

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  generate-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Set the maximum runtime for the job

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

    
      # Install Requirements
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
        continue-on-error: false # Ensure this step fails the workflow if requirements fail

      # Running the Python Script
      - name: Run the Python Script
        run: |
          python3 main.py
        continue-on-error: false # Stop the workflow if the script fails

      # Error Handling (If the job fails)
      - name: Notify on Failure
        if: failure() # Executes only if any previous step fails
        run: |
          echo "Workflow failed. Please check the logs for more details."
